---
kubernetes:
  children:
    master:
      hosts:
        k8s1:
          ansible_host: 10.15.20.40
        k8s2:
          ansible_host: 10.15.20.41
        k8s3:
          ansible_host: 10.15.20.42
    worker:
      hosts:
        k8s4:
          ansible_host: 10.15.20.43
        k8s5:
          ansible_host: 10.15.20.44
        k8s6:
          ansible_host: 10.15.20.45
    lxd-master:
      hosts:
        server1:
          ansible_host: 172.16.70.10
    lxd-workers:
      hosts:
        server2:
          ansible_host: 172.16.70.20
        server3:
          ansible_host: 172.16.70.30
    metal:
      hosts:
        server1:
          ansible_host: 172.16.70.10
          eno1_host: 10.15.20.10
          eno1_dns: 10.15.20.1
        server2:
          ansible_host: 172.16.70.20
          eno1_host: 10.15.20.20
          eno1_dns: 10.15.20.1
        server3:
          ansible_host: 172.16.70.30
          eno1_host: 10.15.20.30
          eno1_dns: 10.15.20.1
